### ISSUE TITLE
Windows binaries 32/64 bit are missing

### ISSUE THREAD

**Issue by yellow-panther** [functionalley/BishBosh#1]
Hello,

can you create a Windows binary (32/64 bit executable file) and host it on your Github website too, please? My pc supports the following instructions: MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, Intel 64, but NOT BMI2

I am not a programmer of course, but write contributions for CCWiki http://computer-chess.org/doku.php

Best wishes,

**Comment by functionalley** [comment]
I hardly ever use **Windows**, but I've just built it on **Windows-10** & uploaded the required changes in version **bishbosh-0.0.0.2**.
If you build the application yourself, then I don't need to be concerned with platforms-specifics.

First you'll need a **Haskell** compiler & basic libraries; that's easy & free.
Go to https://www.haskell.org/platform/windows.html to download the "**Haskell Platform**"; ideally the 64-bit version.

Then you need "**bishbosh**" & all its dependencies, but rather than installing all the dependencies manually,
it's better to use a tool called "**cabal**" from the Haskell platform you just installed, because **cabal** understands the network of dependencies.

Open **Command Prompt**:
	**cabal update**
		Downloading the latest package list from hackage.haskell.org
	**cabal install -f-unix -f-hxtrelaxng bishbosh-0.0.0.2**
		Resolving dependencies... 
		...

You'll also need <https://www.gnu.org/software/xboard/> for the GUI, since thought bisbosh can render a board in an **xterm**, I doubt that'll work in Windows.

The documentation for bishbosh is in **man** format which is hard to read on Windows, but is also available on <https://functionalley.eu/Man/man.html>.
The basic invocation is **xboard -fcp 'bishbosh -i config/CECP/bishbosh_black.xml'**; you'll need to adjust the path to the config-file to where Windows put it. 
The xml config-file references a **PGN** database of standard-openings, which may need some tweaks for Windows also.

**Comment by yellow-panther** [comment]
I am not a programmer, only a tester of chess engines. Where is the exact url (download link) of BishBosh 0.0.0.2 for Windows? I am using Windows 7 SP1 64 bit at the moment.

**Comment by functionalley** [comment]
I haven't made an executable available for any OS; **bishbosh** is merely the source-code, written in a portable language **Haskell** <https://en.wikipedia.org/wiki/Haskell_%28programming_language%29>.

It is typically installed on an arbitrary OS using a tool called **cabal**, which downloads the package from <https://hackage.haskell.org/> & builds it. The package then contains an executable & required ancillary files.

The **cabal** package compiles & works on **GNU/Linux**.
I know it compiles on **MS-Windows**, but am pretty sure it needs debugging, & given my limited enthusiasm for **MS-Windows**, it's probably not going to be me.

The project was largely about me exploring chess-programming using a pure functional language, rather than an attempt to compete with the best programs already available.
