### ISSUE TITLE
countTerminalNodes implementation

### ISSUE THREAD

**Issue by treeowl** [functionalley/BishBosh#2]
I don't know how important `countTerminalNodes` is, but it can be written in a more compact way that I believe will also use a constant factor less stack space:

```haskell
countTerminalNodes :: Num nodes => Data.Tree.Tree a -> nodes
countTerminalNodes = go 0
  where
    go acc Node{subForest = []} = acc + 1
    -- This bang pattern isn't actually necessary in versions of GHC after 7.10 or so
    -- thanks to an accidental change in foldl' strictness.
    go !acc Node{subForest = forest} = foldl' go acc forest
```

The idea is that rather than pushing both the accumulator and the forest tail on the stack each time we descend into a tree, we only need to push the forest tail.

When running on a 64-bit machine it's safe (and potentially much faster) to count with machine words instead:

```haskell
countTerminalNodes :: Num nodes => Data.Tree.Tree a -> nodes
countTerminalNodes
  | finiteBitSize (0 :: Int) >= 61
  = fromIntegral . go (0 :: Int64)
  | otherwise
  = go 0
  where
    go :: Num n => n -> Data.Tree.Tree a -> n
    go acc Node{subForest = []} = acc + 1
    go !acc Node{subForest = forest} = foldl' go acc forest
```

**Comment by functionalley** [comment]
Thanks for that. It's great that anyone took the time to read some of the code let alone make such a cerebral observation.
I won't fully understand the philosophy of your algorithm until I spend some time in a dark place, but I did implement, test it (it does seem to be faster), & commit the change.
Regrettably it won't have any impact on the currently uninspiring speed of BishBosh, since this function is only used to support a test-case (the one I used to test the speed). Besides, BishBosh is bottlenecked by indexing & allocating Arrays.
Regarding the use of machine-width integers; even an int64 would overflow given that the tree is used to represent all possible games of chess. It may not be feasible to count all these games, but it seems conceptually wrong to constrain the function's scope.
